apiVersion: v1
kind: ConfigMap
metadata:
  name: sriov-net-a
  annotations:
    configure-nad: ""
data:
  type: "sriov"
  vlan: 1000
  ipam:
    type: "host-local"
    subnet: "10.56.217.0/24"
    rangeStart: "10.56.217.171"
    rangeEnd: "10.56.217.181"
    gateway: "10.56.217.1"
    routes:
      - dst: "0.0.0.0/0"
